### ISSUE TITLE
CATALOG OF REQUIREMENTS

### ISSUE THREAD

**Issue by j8sanc** [TIS2024-FMFI/autoguider#2]
We have to develop the catalog of requirements

**Comment by pavelpetrovic** [comment]
[Software Requisites Specification - Autoguider Camera_mz_with_comments.docx](https://github.com/user-attachments/files/17575385/Software.Requisites.Specification.-.Autoguider.Camera_mz_with_comments.docx)

**Comment by j8sanc** [comment]
[SRS - Autoguider Camera - Final version.docx](https://github.com/user-attachments/files/17579894/SRS.-.Autoguider.Camera.-.Final.version.docx)
This is my proposal for the final version of the catalog of requirements
